# Generated by Django 5.2.8 on 2025-11-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('movieId', models.IntegerField(primary_key=True, serialize=False)),
                ('imdbId', models.IntegerField(blank=True, null=True)),
                ('tmdbId', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
